In [1]:
import pandas as pd

rain = pd.read_csv("강수량분석자료_20202022.csv", encoding='cp949', )
temp = pd.read_csv('기온분석자료_20202022.csv', encoding='cp949')
humidity = pd.read_csv('습도분석자료_20202022.csv', encoding='cp949')
wind = pd.read_csv('풍속분석자료_20202022.csv', encoding='cp949')

In [2]:
rain

,\t지점번호,지점명,일시,강수량(mm),일최다강수량(mm),일최다강수량일자,1시간최다강수량(mm),1시간최다강수량일자
0,\t108,서울,Jan-20,60.5,46.3,2020-01-07,NaN,NaN
1,\t108,서울,Feb-20,53.1,16.6,2020-02-25,NaN,NaN
2,\t108,서울,Mar-20,16.3,11.8,2020-03-10,NaN,NaN
3,\t108,서울,Apr-20,16.9,10.3,2020-04-19,3.9,2020-04-17
4,\t108,서울,May-20,112.4,29.8,2020-05-18,19.8,2020-05-18
5,\t108,서울,Jun-20,139.6,64.7,2020-06-30,15.9,2020-06-30
6,\t108,서울,Jul-20,270.4,103.1,2020-07-23,27.1,2020-07-29
7,\t108,서울,Aug-20,675.7,102.6,2020-08-03,32.5,2020-08-30
8,\t108,서울,Sep-20,181.5,61.0,2020-09-07,34.0,2020-09-30
9,\t108,서울,Oct-20,0.0,0.0,2020-10-22,0.0,2020-10-22
10,\t108,서울,Nov-20,120.1,86.9,2020-11-19,NaN,NaN
11,\t108,서울,Dec-20,4.6,2.9,2020-12-13,NaN,NaN
12,\t108,서울,Jan-21,18.9,9.2,2021-01-21,NaN,NaN
13,\t108,서울,Feb-21,7.1,3.4,2021-02-03,NaN,NaN
14,\t108,서울,Mar-21,110.9,67.5,2021-03-01,NaN,NaN
15,\t108,서울,Apr-21,124.1,56.2,2021-04-03,11.5,2021-04-03
16,\t108,서울,May-21,183.1,66.9,2021-05-16,11.3,2021-05-30
17,\t108,서울,Jun-21,104.6,38.2,2021-06-27,37.7,2021-06-27
18,\t108,서울,Jul-21,168.3,67.4,2021-07-19,65.7,2021-07-19
19,\t108,서울,Aug-21,211.2,77.4,2021-08-31,27.9,2021-08-21
20,\t108,서울,Sep-21,131.0,68.1,2021-09-21,27.1,2021-09-21
21,\t108,서울,Oct-21,57.0,14.2,2021-10-10,12.7,2021-10-01
22,\t108,서울,Nov-21,62.4,27.2,2021-11-30,NaN,NaN
23,\t108,서울,Dec-21,7.9,2.8,2021-12-18,NaN,NaN
24,\t108,서울,Jan-22,5.5,1.7,2022-01-19,NaN,NaN
25,\t108,서울,Feb-22,4.7,1.7,2022-02-14,NaN,NaN
26,\t108,서울,Mar-22,102.6,42.1,2022-03-13,NaN,NaN
27,\t108,서울,Apr-22,20.4,15.5,2022-04-29,4.0,2022-04-29
28,\t108,서울,May-22,7.5,3.5,2022-05-25,2.9,2022-05-25
29,\t108,서울,Jun-22,393.8,176.2,2022-06-30,34.4,2022-06-23
30,\t108,서울,Jul-22,252.3,114.5,2022-07-13,33.8,2022-07-16
31,\t108,서울,Aug-22,564.8,129.6,2022-08-08,47.1,2022-08-19
32,\t108,서울,Sep-22,201.5,120.0,2022-09-05,12.8,2022-09-05
33,\t108,서울,Oct-22,124.1,76.0,2022-10-03,14.7,2022-10-03
34,\t108,서울,Nov-22,84.5,57.9,2022-11-12,NaN,NaN
35,\t108,서울,Dec-22,13.6,5.4,2022-12-12,NaN,NaN
36,\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,\t\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
temp

,\t\t지점번호,지점명,일시,평균기온(℃),평균최고기온(℃),최고기온(℃),\t최고기온일자,평균최저기온(℃),최저기온(℃),최저기온일자
0,\t\t108,서울,Jan-20,1.6,5.9,11.9,2020-01-26,-1.7,-6.5,2020-01-01
1,\t\t108,서울,Feb-20,2.5,7.2,15.6,2020-02-15,-1.3,-11.8,2020-02-06
2,\t\t108,서울,Mar-20,7.7,13.3,20.6,2020-03-26,2.6,-2.8,2020-03-05
3,\t\t108,서울,Apr-20,11.1,16.6,23.8,2020-04-16,6.3,1.9,2020-04-05
4,\t\t108,서울,May-20,18.0,23.3,30.0,2020-05-30,13.7,9.2,2020-05-20
5,\t\t108,서울,Jun-20,23.9,29.0,35.4,2020-06-22,19.9,14.8,2020-06-02
6,\t\t108,서울,Jul-20,24.1,28.0,32.9,2020-07-09,21.1,17.2,2020-07-14
7,\t\t108,서울,Aug-20,26.5,29.3,34.5,2020-08-26,24.4,21.5,2020-08-23
8,\t\t108,서울,Sep-20,21.4,25.6,29.5,2020-09-01,18.0,13.6,2020-09-21
9,\t\t108,서울,Oct-20,14.3,19.5,23.6,2020-10-01,9.6,3.2,2020-10-24
10,\t\t108,서울,Nov-20,8.0,12.6,20.0,2020-11-17,4.0,-3.6,2020-11-30
11,\t\t108,서울,Dec-20,-0.3,3.9,11.4,2020-12-28,-4.2,-12.9,2020-12-31
12,\t\t108,서울,Jan-21,-2.4,2.2,13.9,2021-01-25,-6.8,-18.6,2021-01-08
13,\t\t108,서울,Feb-21,2.7,7.9,17.4,2021-02-21,-2.2,-10.6,2021-02-18
14,\t\t108,서울,Mar-21,9.0,14.8,22.9,2021-03-31,4.3,-1.2,2021-03-03
15,\t\t108,서울,Apr-21,14.2,19.5,28.2,2021-04-21,9.5,3.1,2021-04-14
16,\t\t108,서울,May-21,17.1,21.9,30.8,2021-05-14,12.8,7.3,2021-05-02
17,\t\t108,서울,Jun-21,22.8,27.6,31.6,2021-06-09,18.9,13.3,2021-06-04
18,\t\t108,서울,Jul-21,28.1,32.2,36.5,2021-07-24,24.6,19.6,2021-07-03
19,\t\t108,서울,Aug-21,25.9,29.7,33.7,2021-08-05,22.8,18.1,2021-08-31
20,\t\t108,서울,Sep-21,22.6,26.9,30.3,2021-09-13,18.8,16.0,2021-09-30
21,\t\t108,서울,Oct-21,15.6,20.5,28.8,2021-10-03,11.6,1.3,2021-10-17
22,\t\t108,서울,Nov-21,8.2,13.1,21.3,2021-11-07,4.0,-3.7,2021-11-23
23,\t\t108,서울,Dec-21,0.6,5.1,13.3,2021-12-08,-3.5,-15.5,2021-12-26
24,\t\t108,서울,Jan-22,-2.2,2.6,8.4,2022-01-24,-6.2,-11.3,2022-01-12
25,\t\t108,서울,Feb-22,-1.1,3.8,11.5,2022-02-28,-5.3,-10.7,2022-02-17
26,\t\t108,서울,Mar-22,7.7,12.7,19.5,2022-03-12,3.2,-3.0,2022-03-06
27,\t\t108,서울,Apr-22,14.8,20.6,28.7,2022-04-26,10.0,3.5,2022-04-03
28,\t\t108,서울,May-22,19.1,25.0,30.7,2022-05-23,13.9,7.9,2022-05-01
29,\t\t108,서울,Jun-22,23.3,27.5,32.7,2022-06-11,19.8,14.9,2022-06-15
30,\t\t108,서울,Jul-22,27.3,31.0,36.1,2022-07-30,24.2,20.8,2022-07-21
31,\t\t108,서울,Aug-22,25.7,28.9,32.9,2022-08-04,23.1,16.1,2022-08-28
32,\t\t108,서울,Sep-22,22.4,27.2,32.5,2022-09-18,18.2,12.3,2022-09-24
33,\t\t108,서울,Oct-22,14.6,19.7,27.6,2022-10-01,10.3,4.4,2022-10-19
34,\t\t108,서울,Nov-22,10.0,15.4,22.1,2022-11-11,5.6,-8.1,2022-11-30
35,\t\t108,서울,Dec-22,-2.8,1.7,10.2,2022-12-09,-6.6,-13.7,2022-12-23
36,\t\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,\t\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
humidity

   \t\t지점번호  지점명      일시  평균습도(%rh)  최저습도(%rh)
0   \t\t108   서울  Jan-20       56.0       17.0
1   \t\t108   서울  Feb-20       58.0       14.0
2   \t\t108   서울  Mar-20       46.0       11.0
3   \t\t108   서울  Apr-20       50.0       10.0
4   \t\t108   서울  May-20       67.0       11.0
5   \t\t108   서울  Jun-20       68.0       26.0
6   \t\t108   서울  Jul-20       77.0       34.0
7   \t\t108   서울  Aug-20       85.0       49.0
8   \t\t108   서울  Sep-20       71.0       27.0
9   \t\t108   서울  Oct-20       61.0       20.0
10  \t\t108   서울  Nov-20       64.0       18.0
11  \t\t108   서울  Dec-20       58.0       24.0
12  \t\t108   서울  Jan-21       58.0       19.0
13  \t\t108   서울  Feb-21       56.0       18.0
14  \t\t108   서울  Mar-21       63.0       19.0
15  \t\t108   서울  Apr-21       54.0       18.0
16  \t\t108   서울  May-21       68.0       25.0
17  \t\t108   서울  Jun-21       73.0       36.0
18  \t\t108   서울  Jul-21       71.0       37.0
19  \t\t108   서울  Aug-21       74.0       39.0
20  \t\t108   서울  Sep-21       71.0       38.0
21  \t\t108   서울  Oct-21       70.0       25.0
22  \t\t108   서울  Nov-21       68.0       27.0
23  \t\t108   서울  Dec-21       62.0       26.0
24  \t\t108   서울  Jan-22       55.0       21.0
25  \t\t108   서울  Feb-22       55.0       21.0
26  \t\t108   서울  Mar-22       62.0       15.0
27  \t\t108   서울  Apr-22       55.0       17.0
28  \t\t108   서울  May-22       55.0       16.0
29  \t\t108   서울  Jun-22       73.0       18.0
30  \t\t108   서울  Jul-22       77.0       46.0
31  \t\t108   서울  Aug-22       80.0       39.0
32  \t\t108   서울  Sep-22       68.0       29.0
33  \t\t108   서울  Oct-22       69.0       25.0
34  \t\t108   서울  Nov-22       65.0       23.0
35  \t\t108   서울  Dec-22       59.0       21.0
36     \t\t  NaN     NaN        NaN        NaN
37       \t  NaN     NaN        NaN        NaN
38       \t  NaN     NaN        NaN        NaN

In [4]:
wind

,\t\t지점번호,지점명,일시,평균풍속(m/s),최대풍속(m/s),최대풍속풍향(deg),\t최대풍속일자,최대순간풍속(m/s),최대순간풍속풍향(deg),\t최대순간풍속일자,\t
0,\t\t108,서울,Jan-20,2.1,7.0,70.0,2020-01-27,13.7,90.0,2020-01-27,NaN
1,\t\t108,서울,Feb-20,2.3,8.2,320.0,2020-02-22,14.4,290.0,2020-02-22,NaN
2,\t\t108,서울,Mar-20,2.5,8.2,250.0,2020-03-19,16.3,270.0,2020-03-19,NaN
3,\t\t108,서울,Apr-20,3.0,8.9,290.0,2020-04-21,17.0,230.0,2020-04-21,NaN
4,\t\t108,서울,May-20,2.4,7.2,70.0,2020-05-19,16.4,290.0,2020-05-18,NaN
5,\t\t108,서울,Jun-20,2.3,7.6,50.0,2020-06-30,14.5,50.0,2020-06-30,NaN
6,\t\t108,서울,Jul-20,2.4,8.7,50.0,2020-07-24,16.1,50.0,2020-07-24,NaN
7,\t\t108,서울,Aug-20,2.3,8.3,180.0,2020-08-03,15.6,140.0,2020-08-27,NaN
8,\t\t108,서울,Sep-20,2.5,9.8,270.0,2020-09-03,21.5,290.0,2020-09-03,NaN
9,\t\t108,서울,Oct-20,2.1,7.2,320.0,2020-10-04,13.7,320.0,2020-10-04,NaN
10,\t\t108,서울,Nov-20,2.2,8.4,290.0,2020-11-03,15.6,290.0,2020-11-03,NaN
11,\t\t108,서울,Dec-20,2.2,6.5,290.0,2020-12-24,11.7,290.0,2020-12-24,NaN
12,\t\t108,서울,Jan-21,2.5,8.7,250.0,2021-01-28,17.5,270.0,2021-01-28,NaN
13,\t\t108,서울,Feb-21,2.6,7.5,270.0,2021-02-17,15.8,270.0,2021-02-17,NaN
14,\t\t108,서울,Mar-21,2.4,6.9,230.0,2021-03-22,14.8,320.0,2021-03-21,NaN
15,\t\t108,서울,Apr-21,2.6,7.1,290.0,2021-04-17,12.5,180.0,2021-04-17,NaN
16,\t\t108,서울,May-21,2.4,8.4,200.0,2021-05-08,16.0,270.0,2021-05-30,NaN
17,\t\t108,서울,Jun-21,2.2,7.8,200.0,2021-06-27,15.0,180.0,2021-06-22,NaN
18,\t\t108,서울,Jul-21,2.0,7.4,50.0,2021-07-16,16.5,360.0,2021-07-16,NaN
19,\t\t108,서울,Aug-21,2.1,8.3,320.0,2021-08-06,16.4,290.0,2021-08-06,NaN
20,\t\t108,서울,Sep-21,2.3,7.1,320.0,2021-09-21,12.5,110.0,2021-09-20,NaN
21,\t\t108,서울,Oct-21,2.1,10.6,290.0,2021-10-01,20.9,320.0,2021-10-01,NaN
22,\t\t108,서울,Nov-21,2.1,9.3,270.0,2021-11-08,16.6,270.0,2021-11-08,NaN
23,\t\t108,서울,Dec-21,2.3,8.1,290.0,2021-12-17,15.2,320.0,2021-12-17,NaN
24,\t\t108,서울,Jan-22,2.2,7.6,270.0,2022-01-13,13.9,320.0,2022-01-13,NaN
25,\t\t108,서울,Feb-22,2.6,7.4,250.0,2022-02-27,14.5,290.0,2022-02-26,NaN
26,\t\t108,서울,Mar-22,2.5,8.8,180.0,2022-03-04,18.5,180.0,2022-03-04,NaN
27,\t\t108,서울,Apr-22,2.7,8.4,50.0,2022-04-13,14.5,50.0,2022-04-13,NaN
28,\t\t108,서울,May-22,2.6,7.6,200.0,2022-05-26,14.1,230.0,2022-05-01,NaN
29,\t\t108,서울,Jun-22,2.5,9.9,200.0,2022-06-28,20.9,180.0,2022-06-28,NaN
30,\t\t108,서울,Jul-22,2.1,5.6,160.0,2022-07-30,11.6,230.0,2022-07-06,NaN
31,\t\t108,서울,Aug-22,2.3,8.6,200.0,2022-08-08,24.9,180.0,2022-08-08,NaN
32,\t\t108,서울,Sep-22,2.4,8.0,50.0,2022-09-14,18.3,20.0,2022-09-05,NaN
33,\t\t108,서울,Oct-22,2.2,6.8,270.0,2022-10-10,13.7,200.0,2022-10-03,NaN
34,\t\t108,서울,Nov-22,2.1,6.5,290.0,2022-11-30,12.0,270.0,2022-11-29,NaN
35,\t\t108,서울,Dec-22,2.3,7.4,290.0,2022-12-13,15.0,290.0,2022-12-22,NaN
36,\t\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,\t\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,\t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# 데이터에서 필요한 칼럼만 가져오기
new_columns = ['일시', '일최다강수량(mm)']
rain = rain[new_columns]

t_new_columns = ['평균최고기온(℃)', '평균최저기온(℃)']
temp = temp[t_new_columns]
wind = wind['최대풍속(m/s)']
humidity = humidity['최저습도(%rh)']


# 행 기준으로 데이터프레임 합치기
df = pd.concat([rain, temp, wind, humidity], axis=1)
df

        일시  일최다강수량(mm)  평균최고기온(℃)  평균최저기온(℃)  최대풍속(m/s)  최저습도(%rh)
0   Jan-20        46.3        5.9       -1.7        7.0       17.0
1   Feb-20        16.6        7.2       -1.3        8.2       14.0
2   Mar-20        11.8       13.3        2.6        8.2       11.0
3   Apr-20        10.3       16.6        6.3        8.9       10.0
4   May-20        29.8       23.3       13.7        7.2       11.0
5   Jun-20        64.7       29.0       19.9        7.6       26.0
6   Jul-20       103.1       28.0       21.1        8.7       34.0
7   Aug-20       102.6       29.3       24.4        8.3       49.0
8   Sep-20        61.0       25.6       18.0        9.8       27.0
9   Oct-20         0.0       19.5        9.6        7.2       20.0
10  Nov-20        86.9       12.6        4.0        8.4       18.0
11  Dec-20         2.9        3.9       -4.2        6.5       24.0
12  Jan-21         9.2        2.2       -6.8        8.7       19.0
13  Feb-21         3.4        7.9       -2.2        7.5       18.0
14  Mar-21        67.5       14.8        4.3        6.9       19.0
15  Apr-21        56.2       19.5        9.5        7.1       18.0
16  May-21        66.9       21.9       12.8        8.4       25.0
17  Jun-21        38.2       27.6       18.9        7.8       36.0
18  Jul-21        67.4       32.2       24.6        7.4       37.0
19  Aug-21        77.4       29.7       22.8        8.3       39.0
20  Sep-21        68.1       26.9       18.8        7.1       38.0
21  Oct-21        14.2       20.5       11.6       10.6       25.0
22  Nov-21        27.2       13.1        4.0        9.3       27.0
23  Dec-21         2.8        5.1       -3.5        8.1       26.0
24  Jan-22         1.7        2.6       -6.2        7.6       21.0
25  Feb-22         1.7        3.8       -5.3        7.4       21.0
26  Mar-22        42.1       12.7        3.2        8.8       15.0
27  Apr-22        15.5       20.6       10.0        8.4       17.0
28  May-22         3.5       25.0       13.9        7.6       16.0
29  Jun-22       176.2       27.5       19.8        9.9       18.0
30  Jul-22       114.5       31.0       24.2        5.6       46.0
31  Aug-22       129.6       28.9       23.1        8.6       39.0
32  Sep-22       120.0       27.2       18.2        8.0       29.0
33  Oct-22        76.0       19.7       10.3        6.8       25.0
34  Nov-22        57.9       15.4        5.6        6.5       23.0
35  Dec-22         5.4        1.7       -6.6        7.4       21.0
36     NaN         NaN        NaN        NaN        NaN        NaN
37     NaN         NaN        NaN        NaN        NaN        NaN
38     NaN         NaN        NaN        NaN        NaN        NaN
39     NaN         NaN        NaN        NaN        NaN        NaN
40     NaN         NaN        NaN        NaN        NaN        NaN
41     NaN         NaN        NaN        NaN        NaN        NaN
42     NaN         NaN        NaN        NaN        NaN        NaN
43     NaN         NaN        NaN        NaN        NaN        NaN

In [7]:
# NaN 값 삭제
df = df.dropna()

# 데이터 저장
df.to_csv('날씨데이터총합_변경.csv', encoding='cp949', index=False)

In [8]:
data = pd.read_csv('날씨데이터총합_변경.csv', encoding='cp949', index_col=0)
data

        일최다강수량(mm)  평균최고기온(℃)  평균최저기온(℃)  최대풍속(m/s)  최저습도(%rh)
일시
Jan-20        46.3        5.9       -1.7        7.0       17.0
Feb-20        16.6        7.2       -1.3        8.2       14.0
Mar-20        11.8       13.3        2.6        8.2       11.0
Apr-20        10.3       16.6        6.3        8.9       10.0
May-20        29.8       23.3       13.7        7.2       11.0
Jun-20        64.7       29.0       19.9        7.6       26.0
Jul-20       103.1       28.0       21.1        8.7       34.0
Aug-20       102.6       29.3       24.4        8.3       49.0
Sep-20        61.0       25.6       18.0        9.8       27.0
Oct-20         0.0       19.5        9.6        7.2       20.0
Nov-20        86.9       12.6        4.0        8.4       18.0
Dec-20         2.9        3.9       -4.2        6.5       24.0
Jan-21         9.2        2.2       -6.8        8.7       19.0
Feb-21         3.4        7.9       -2.2        7.5       18.0
Mar-21        67.5       14.8        4.3        6.9       19.0
Apr-21        56.2       19.5        9.5        7.1       18.0
May-21        66.9       21.9       12.8        8.4       25.0
Jun-21        38.2       27.6       18.9        7.8       36.0
Jul-21        67.4       32.2       24.6        7.4       37.0
Aug-21        77.4       29.7       22.8        8.3       39.0
Sep-21        68.1       26.9       18.8        7.1       38.0
Oct-21        14.2       20.5       11.6       10.6       25.0
Nov-21        27.2       13.1        4.0        9.3       27.0
Dec-21         2.8        5.1       -3.5        8.1       26.0
Jan-22         1.7        2.6       -6.2        7.6       21.0
Feb-22         1.7        3.8       -5.3        7.4       21.0
Mar-22        42.1       12.7        3.2        8.8       15.0
Apr-22        15.5       20.6       10.0        8.4       17.0
May-22         3.5       25.0       13.9        7.6       16.0
Jun-22       176.2       27.5       19.8        9.9       18.0
Jul-22       114.5       31.0       24.2        5.6       46.0
Aug-22       129.6       28.9       23.1        8.6       39.0
Sep-22       120.0       27.2       18.2        8.0       29.0
Oct-22        76.0       19.7       10.3        6.8       25.0
Nov-22        57.9       15.4        5.6        6.5       23.0
Dec-22         5.4        1.7       -6.6        7.4       21.0

In [9]:
# 인덱스 rename
data = data.rename(index={'Jan-20':202001, 'Feb-20':202002, 'Mar-20':202003, 'Apr-20':202004, 'May-20':202005, 'Jun-20':202006, 'Jul-20':202007, 'Aug-20':202008, 'Sep-20':202009, 'Oct-20':202010, 'Nov-20':202011, 'Dec-20':202012, 
                          'Jan-21':202101, 'Feb-21':202102, 'Mar-21':202103, 'Apr-21':202104, 'May-21':202105, 'Jun-21':202106, 'Jul-21':202107, 'Aug-21':202108, 'Sep-21':202109, 'Oct-21':202110, 'Nov-21':202111, 'Dec-21':202112, 
                          'Jan-22':202201, 'Feb-22':202202, 'Mar-22':202203, 'Apr-22':202204, 'May-22':202205, 'Jun-22':202206, 'Jul-22':202207, 'Aug-22':202208, 'Sep-22':202209, 'Oct-22':202210, 'Nov-22':202211, 'Dec-22':202212})
data

        일최다강수량(mm)  평균최고기온(℃)  평균최저기온(℃)  최대풍속(m/s)  최저습도(%rh)
일시
202001        46.3        5.9       -1.7        7.0       17.0
202002        16.6        7.2       -1.3        8.2       14.0
202003        11.8       13.3        2.6        8.2       11.0
202004        10.3       16.6        6.3        8.9       10.0
202005        29.8       23.3       13.7        7.2       11.0
202006        64.7       29.0       19.9        7.6       26.0
202007       103.1       28.0       21.1        8.7       34.0
202008       102.6       29.3       24.4        8.3       49.0
202009        61.0       25.6       18.0        9.8       27.0
202010         0.0       19.5        9.6        7.2       20.0
202011        86.9       12.6        4.0        8.4       18.0
202012         2.9        3.9       -4.2        6.5       24.0
202101         9.2        2.2       -6.8        8.7       19.0
202102         3.4        7.9       -2.2        7.5       18.0
202103        67.5       14.8        4.3        6.9       19.0
202104        56.2       19.5        9.5        7.1       18.0
202105        66.9       21.9       12.8        8.4       25.0
202106        38.2       27.6       18.9        7.8       36.0
202107        67.4       32.2       24.6        7.4       37.0
202108        77.4       29.7       22.8        8.3       39.0
202109        68.1       26.9       18.8        7.1       38.0
202110        14.2       20.5       11.6       10.6       25.0
202111        27.2       13.1        4.0        9.3       27.0
202112         2.8        5.1       -3.5        8.1       26.0
202201         1.7        2.6       -6.2        7.6       21.0
202202         1.7        3.8       -5.3        7.4       21.0
202203        42.1       12.7        3.2        8.8       15.0
202204        15.5       20.6       10.0        8.4       17.0
202205         3.5       25.0       13.9        7.6       16.0
202206       176.2       27.5       19.8        9.9       18.0
202207       114.5       31.0       24.2        5.6       46.0
202208       129.6       28.9       23.1        8.6       39.0
202209       120.0       27.2       18.2        8.0       29.0
202210        76.0       19.7       10.3        6.8       25.0
202211        57.9       15.4        5.6        6.5       23.0
202212         5.4        1.7       -6.6        7.4       21.0

In [11]:
data.to_csv('날씨데이터총합_변경.csv', encoding='cp949')