In [2]:
pip install prophet

Collecting prophetNote: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 23.3.2 is available.
You should consider upgrading via the 'c:\Users\DB-26\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

  Downloading prophet-1.1.5-py3-none-win_amd64.whl (13.3 MB)
Requirement already satisfied: matplotlib>=2.0.0 in c:\users\db-26\appdata\local\programs\python\python39\lib\site-packages (from prophet) (3.8.0)
Collecting tqdm>=4.36.1
  Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
Requirement already satisfied: importlib-resources in c:\users\db-26\appdata\local\programs\python\python39\lib\site-packages (from prophet) (6.1.0)
Collecting holidays>=0.25
  Downloading holidays-0.39-py3-none-any.whl (869 kB)
Requirement already satisfied: numpy>=1.15.4 in c:\users\db-26\appdata\local\programs\python\python39\lib\site-packages (from prophet) (1.26.0)
Requirement already satisfied: pandas>=1.0.4 in c:\users\db-26\appdata\local\programs\python\python39\lib\site-packages (from prophet) (2.1.1)
Collecting cmdstanpy>=1.0.4
  Downloading cmdstanpy-1.2.0-py3-none-any.whl (93 kB)
Collecting stanio~=0.3.0
  Downloading stanio-0.3.0-py3-none-any.whl (6.2 kB)
Requirement already satisfied: python-dateutil in c:\users\db-26\appdata\roaming\python\python39\site-packages (from holidays>=0.25->prophet) (2.8.2)
Requirement already satisfied: packaging>=20.0 in c:\users\db-26\appdata\roaming\python\python39\site-packages (from matplotlib>=2.0.0->prophet) (23.1)
Requirement already satisfied: cycler>=0.10 in c:\users\db-26\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=2.0.0->prophet) (0.12.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\db-26\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=2.0.0->prophet) (10.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\db-26\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=2.0.0->prophet) (1.4.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\db-26\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=2.0.0->prophet) (1.1.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\db-26\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=2.0.0->prophet) (4.43.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\db-26\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=2.0.0->prophet) (3.1.1)
Requirement already satisfied: zipp>=3.1.0 in c:\users\db-26\appdata\roaming\python\python39\site-packages (from importlib-resources->prophet) (3.16.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\db-26\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.0.4->prophet) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\db-26\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.0.4->prophet) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\db-26\appdata\roaming\python\python39\site-packages (from python-dateutil->holidays>=0.25->prophet) (1.16.0)
Requirement already satisfied: colorama in c:\users\db-26\appdata\roaming\python\python39\site-packages (from tqdm>=4.36.1->prophet) (0.4.6)
Installing collected packages: tqdm, stanio, holidays, cmdstanpy, prophet
Successfully installed cmdstanpy-1.2.0 holidays-0.39 prophet-1.1.5 stanio-0.3.0 tqdm-4.66.1

In [3]:
from prophet import Prophet
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

import datetime
import warnings

warnings.filterwarnings('always')
warnings.filterwarnings('ignore')

c:\Users\DB-26\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Importing plotly failed. Interactive plots will not work.

In [8]:
df = pd.read_csv('년,월별 총 범죄데이터.csv', encoding='cp949', index_col=0)
df.head()

,20년1월_범죄건수,21년1월_범죄건수,22년1월_범죄건수,20년2월_범죄건수,21년2월_범죄건수,22년2월_범죄건수,20년3월_범죄건수,21년3월_범죄건수,22년3월_범죄건수,20년4월_범죄건수,...,22년9월_범죄건수,20년10월_범죄건수,21년10월_범죄건수,22년10월_범죄건수,20년11월_범죄건수,21년11월_범죄건수,22년11월_범죄건수,20년12월_범죄건수,21년12월_범죄건수,22년12월_범죄건수
자치구,,,,,,,,,,,,,,,,,,,,,
강남구,715,438,569,508,338,398,679,487,518,604,...,549,519,548,580,592,634,706,606,518,630
강동구,332,242,324,287,196,222,283,265,244,264,...,298,310,241,270,312,375,450,292,344,303
강북구,258,141,217,242,128,152,258,167,204,252,...,244,212,201,240,182,227,241,183,191,214
강서구,443,258,353,373,223,262,421,286,357,330,...,368,377,359,471,297,387,434,289,402,343
관악구,466,304,378,365,287,284,396,331,310,456,...,329,469,296,395,431,470,600,461,450,461

In [9]:
df.columns

Index(['20년1월_범죄건수', '21년1월_범죄건수', '22년1월_범죄건수', '20년2월_범죄건수', '21년2월_범죄건수',
       '22년2월_범죄건수', '20년3월_범죄건수', '21년3월_범죄건수', '22년3월_범죄건수', '20년4월_범죄건수',
       '21년4월_범죄건수', '22년4월_범죄건수', '20년5월_범죄건수', '21년5월_범죄건수', '22년5월_범죄건수',
       '20년6월_범죄건수', '21년6월_범죄건수', '22년6월_범죄건수', '20년7월_범죄건수', '21년7월_범죄건수',
       '22년7월_범죄건수', '20년8월_범죄건수', '21년8월_범죄건수', '22년8월_범죄건수', '20년9월_범죄건수',
       '21년9월_범죄건수', '22년9월_범죄건수', '20년10월_범죄건수', '21년10월_범죄건수', '22년10월_범죄건수',
       '20년11월_범죄건수', '21년11월_범죄건수', '22년11월_범죄건수', '20년12월_범죄건수',
       '21년12월_범죄건수', '22년12월_범죄건수'],
      dtype='object')

In [10]:
pattern = ['20년', '21년', '22년']
months = [f'{month}월' for month in range(1, 13)]
sorted_columns = [f'{year}{month}_범죄건수' for year in pattern for month in months]

# 패턴에 따라 칼럼 이름 정렬
df = df.reindex(columns=sorted_columns)

In [11]:
df.head()

,20년1월_범죄건수,20년2월_범죄건수,20년3월_범죄건수,20년4월_범죄건수,20년5월_범죄건수,20년6월_범죄건수,20년7월_범죄건수,20년8월_범죄건수,20년9월_범죄건수,20년10월_범죄건수,...,22년3월_범죄건수,22년4월_범죄건수,22년5월_범죄건수,22년6월_범죄건수,22년7월_범죄건수,22년8월_범죄건수,22년9월_범죄건수,22년10월_범죄건수,22년11월_범죄건수,22년12월_범죄건수
자치구,,,,,,,,,,,,,,,,,,,,,
강남구,715,508,679,604,582,631,641,651,296,519,...,518,534,617,579,624,643,549,580,706,630
강동구,332,287,283,264,299,330,373,357,89,310,...,244,273,313,325,360,329,298,270,450,303
강북구,258,242,258,252,243,253,265,222,210,212,...,204,231,302,295,230,262,244,240,241,214
강서구,443,373,421,330,371,371,369,380,139,377,...,357,379,382,416,465,433,368,471,434,343
관악구,466,365,396,456,459,441,494,2409,252,469,...,310,392,355,423,463,489,329,395,600,461

In [14]:
data = df.T
data.to_csv('시계열분석_전처리.csv', encoding='cp949')
data.head()

자치구,강남구,강동구,강북구,강서구,관악구,광진구,구로구,금천구,노원구,도봉구,...,성동구,성북구,송파구,양천구,영등포구,용산구,은평구,종로구,중구,중랑구
20년1월_범죄건수,715,332,258,443,466,344,394,222,274,188,...,239,216,515,255,489,277,329,296,416,280
20년2월_범죄건수,508,287,242,373,365,251,262,264,274,166,...,164,186,337,265,395,209,242,228,267,275
20년3월_범죄건수,679,283,258,421,396,297,322,239,266,169,...,173,220,473,239,440,282,277,310,326,333
20년4월_범죄건수,604,264,252,330,456,276,310,193,306,176,...,194,217,475,238,412,291,259,211,230,292
20년5월_범죄건수,582,299,243,371,459,290,386,233,370,170,...,177,185,515,244,493,266,259,253,258,301

In [13]:
df = pd.read_csv('시계열분석_전처리.csv', encoding='cp949')
df1 = pd.read_csv('시계열_전처리_20-21.csv', encoding='utf-8')
df2 = pd.read_csv('시계열_전처리_22.csv', encoding='utf-8')
df.head()

,Date,강남구,강동구,강북구,강서구,관악구,광진구,구로구,금천구,노원구,...,성동구,성북구,송파구,양천구,영등포구,용산구,은평구,종로구,중구,중랑구
0,20년1월_범죄건수,715,332,258,443,466,344,394,222,274,...,239,216,515,255,489,277,329,296,416,280
1,20년2월_범죄건수,508,287,242,373,365,251,262,264,274,...,164,186,337,265,395,209,242,228,267,275
2,20년3월_범죄건수,679,283,258,421,396,297,322,239,266,...,173,220,473,239,440,282,277,310,326,333
3,20년4월_범죄건수,604,264,252,330,456,276,310,193,306,...,194,217,475,238,412,291,259,211,230,292
4,20년5월_범죄건수,582,299,243,371,459,290,386,233,370,...,177,185,515,244,493,266,259,253,258,301

In [14]:
# '범죄건수' 문자열 삭제
df['Date'] = df['Date'].str.replace('_범죄건수', '')

df['Date'] = df['Date'].str.replace(r'(\d+)년(\d+)월', r'20\1\2', regex=True)

df['Date'] = pd.to_datetime(df['Date'], format='%Y%m').dt.strftime('%Y%m')

df.head()

,Date,강남구,강동구,강북구,강서구,관악구,광진구,구로구,금천구,노원구,...,성동구,성북구,송파구,양천구,영등포구,용산구,은평구,종로구,중구,중랑구
0,202001,715,332,258,443,466,344,394,222,274,...,239,216,515,255,489,277,329,296,416,280
1,202002,508,287,242,373,365,251,262,264,274,...,164,186,337,265,395,209,242,228,267,275
2,202003,679,283,258,421,396,297,322,239,266,...,173,220,473,239,440,282,277,310,326,333
3,202004,604,264,252,330,456,276,310,193,306,...,194,217,475,238,412,291,259,211,230,292
4,202005,582,299,243,371,459,290,386,233,370,...,177,185,515,244,493,266,259,253,258,301

In [15]:
# '범죄건수' 문자열 삭제
df1['Date'] = df1['Date'].str.replace('_범죄건수', '')

df1['Date'] = df1['Date'].str.replace(r'(\d+)년(\d+)월', r'20\1\2', regex=True)

df1['Date'] = pd.to_datetime(df1['Date'], format='%Y%m').dt.strftime('%Y%m')

In [16]:
# '범죄건수' 문자열 삭제
df2['Date'] = df2['Date'].str.replace('_범죄건수', '')

df2['Date'] = df2['Date'].str.replace(r'(\d+)년(\d+)월', r'20\1\2', regex=True)

df2['Date'] = pd.to_datetime(df2['Date'], format='%Y%m').dt.strftime('%Y%m')

In [17]:
# 정확도 검증

gu_name = ['강남구', 'Date']

last_2year = list()
for i in range(2022, 2024):
    for j in range(1, 13):
        last_2year.append(['%04d-%02d' % (i,j)])
        
        
last_2year = pd.DataFrame(last_2year, columns = ['ds'])
last_2year['ds']= pd.to_datetime(last_2year['ds'])

for i in range(len(df1['Date'])):
    date_time_str = df1['Date'][i]
    
    date = datetime.datetime.strptime(str(date_time_str), '%Y%m')  #datetime.datetime.strptime(date, "%Y-%m-%d")
    
    df1['Date'][i] = date

gangnam_predict = pd.DataFrame()

for i,name in enumerate(gu_name):
    data = pd.DataFrame()
    data = df1[[name,'Date']]
    data.columns = ['y','ds']
    data['ds'] = pd.to_datetime(data['ds'])

    model = Prophet().fit(data)
    print(i,"model_fit")
    forecast = model.predict(last_2year)
    print(i,"model_predict")
    gangnam_predict = pd.concat([gangnam_predict, forecast['yhat']], ignore_index = True, axis=1)

03:12:31 - cmdstanpy - INFO - Chain [1] start processing
03:12:32 - cmdstanpy - INFO - Chain [1] done processing

0 model_fit
0 model_predict

TypeError: Invalid object type at position 0

In [18]:
gangnam_predict = pd.concat([gangnam_predict, forecast['ds']], ignore_index = True, axis=1)

gangnam_predict.columns = ['강남구', 'Date']

gangnam_predict.to_csv('gangnam_predict_20-21.csv', encoding='cp949',index = False)

In [22]:
predict_2021 = pd.read_csv('gangnam_predict_20-21.csv', encoding='cp949')
predict_22 = pd.read_csv('gangnam_predict_22.csv', encoding='cp949')

predict_22

          Date         강남구
0   2022-01-01  498.444374
1   2022-02-01  494.348852
2   2022-03-01  490.649671
3   2022-04-01  486.554149
4   2022-05-01  482.590740
5   2022-06-01  478.495219
6   2022-07-01  474.531810
7   2022-08-01  470.436288
8   2022-09-01  466.340766
9   2022-10-01  462.377358
10  2022-11-01  458.281836
11  2022-12-01  454.318428

In [20]:
df2

,Date,강남구,강동구,강북구,강서구,관악구,광진구,구로구,금천구,노원구,...,성동구,성북구,송파구,양천구,영등포구,용산구,은평구,종로구,중구,중랑구
0,202201,569,324,217,353,378,365,330,249,265,...,382,192,444,304,414,235,319,243,250,212
1,202202,398,222,152,262,284,180,221,144,175,...,294,109,271,175,282,169,214,187,181,181
2,202203,518,244,204,357,310,241,261,169,197,...,320,147,398,226,360,183,265,199,268,177
3,202204,534,273,231,379,392,308,284,165,211,...,347,191,411,281,377,177,277,211,324,218
4,202205,617,313,302,382,355,309,348,202,265,...,406,187,425,263,432,246,280,249,297,287
5,202206,579,325,295,416,423,338,391,252,283,...,395,213,489,296,435,298,328,266,323,300
6,202207,624,360,230,465,463,298,347,284,284,...,392,219,416,259,433,312,287,226,347,261
7,202208,643,329,262,433,489,286,372,238,288,...,339,221,470,347,412,274,312,150,202,206
8,202209,549,298,244,368,329,297,309,194,268,...,383,142,403,216,324,252,291,211,315,263
9,202210,580,270,240,471,395,292,361,247,232,...,380,180,431,255,335,245,325,237,348,272
10,202211,706,450,241,434,600,382,356,261,309,...,457,209,537,291,599,302,312,275,299,417
11,202212,630,303,214,343,461,323,277,172,294,...,364,184,472,256,416,274,277,208,312,257

In [24]:
correct_predictions = sum(a == p for a, p in zip(df2['강남구'], predict_22['강남구']))
accuracy = correct_predictions / len(df2['강남구']) * 100

print(f'정확도: {accuracy:.2f}%')

정확도: 0.00%

In [25]:
def calculate_mse(actual, predicted):
    squared_errors = [(a - p) ** 2 for a, p in zip(actual, predicted)]
    mse = sum(squared_errors) / len(actual)
    return mse

# MSE 계산
mse = calculate_mse(df2['강남구'], predict_22['강남구'])

print(f'MSE: {mse:.2f}')

MSE: 17536.86

In [42]:
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import cohen_kappa_score
from scipy.stats import spearmanr

predict_22['강남구'] = predict_22['강남구'].astype(float)
df2['강남구'] = df2['강남구'].astype(float)

accuracy_df = accuracy_score(df2['강남구'], predict_22['강남구'])
kappa_df = cohen_kappa_score(df2['강남구'], predict_22['강남구'])
spearman_corr_df = spearmanr(df2['강남구'], predict_22['강남구'])

print('정확도:', accuracy_df)
print('코헨의 카파:', kappa_df)
print('스피어만 순위 상관계수:', spearman_corr_df)

정확도: 1.0
코헨의 카파: nan
스피어만 순위 상관계수: SignificanceResult(statistic=nan, pvalue=nan)

In [31]:
df2['강남구'].dtype

dtype('int64')

In [32]:
predict_22['강남구'].dtype

dtype('float64')

In [36]:
predict_22['강남구'].astype(int)
df2['강남구'].astype(int)

0     569
1     398
2     518
3     534
4     617
5     579
6     624
7     643
8     549
9     580
10    706
11    630
Name: 강남구, dtype: int32

In [39]:
from sklearn.metrics import accuracy_score, cohen_kappa_score
from scipy.stats import spearmanr

# 예측값과 실제값의 데이터 타입 확인
print(df2['강남구'].dtype)
print(predict_22['강남구'].dtype)

# 연속형 데이터인 경우 spearman_corr_df 계산
if df2['강남구'].dtype in [float, int] and predict_22['강남구'].dtype in [float, int]:
    spearman_corr_df, _ = spearmanr(df2['강남구'], predict_22['강남구'])
    print('스피어만 순위 상관계수:', spearman_corr_df)
else:
    print('스피어만 순위 상관계수는 연속형 데이터에 대해서만 계산 가능합니다.')

# 다중 클래스 분류일 경우 accuracy_df, kappa_df 계산
if df2['강남구'].nunique() > 2 and predict_22['강남구'].nunique() > 2:
    accuracy_df = accuracy_score(df2['강남구'], predict_22['강남구'])
    kappa_df = cohen_kappa_score(df2['강남구'], predict_22['강남구'])
    print('정확도:', accuracy_df)
    print('코헨의 카파:', kappa_df)
else:
    print('다중 클래스 분류일 때만 정확도와 코헨의 카파를 계산할 수 있습니다.')

int64
float64
스피어만 순위 상관계수는 연속형 데이터에 대해서만 계산 가능합니다.

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

In [84]:
gu_name = ['강남구', 'Date']

last_3year = list()
for i in range(2023, 2027):
    for j in range(1, 13):
        last_3year.append(['%04d-%02d' % (i,j)])
        
# for i in range(2026, 2027):
#     for j in range(1, 5):
#         last_3year.append(['%04d-%02d' % (i,j)])
        
last_3year = pd.DataFrame(last_3year, columns = ['ds'])
last_3year['ds']= pd.to_datetime(last_3year['ds'])

In [85]:
pd.to_datetime(df['Date'], format='%Y%m')

0    2020-01-01
1    2020-02-01
2    2020-03-01
3    2020-04-01
4    2020-05-01
5    2020-06-01
6    2020-07-01
7    2020-08-01
8    2020-09-01
9    2020-10-01
10   2020-11-01
11   2020-12-01
12   2021-01-01
13   2021-02-01
14   2021-03-01
15   2021-04-01
16   2021-05-01
17   2021-06-01
18   2021-07-01
19   2021-08-01
20   2021-09-01
21   2021-10-01
22   2021-11-01
23   2021-12-01
24   2022-01-01
25   2022-02-01
26   2022-03-01
27   2022-04-01
28   2022-05-01
29   2022-06-01
30   2022-07-01
31   2022-08-01
32   2022-09-01
33   2022-10-01
34   2022-11-01
35   2022-12-01
Name: Date, dtype: datetime64[ns]

In [86]:
for i in range(len(df['Date'])):
    date_time_str = df['Date'][i]
    
    date = datetime.datetime.strptime(str(date_time_str), '%Y%m')  #datetime.datetime.strptime(date, "%Y-%m-%d")
    
    df['Date'][i] = date

In [87]:
gangnam_predict = pd.DataFrame()

for i,name in enumerate(gu_name):
    data = pd.DataFrame()
    data = df[[name,'Date']]
    data.columns = ['y','ds']
#    data['ds'] = pd.to_numeric(data['ds'])
    data['ds'] = pd.to_datetime(data['ds'])
#    data = df.apply(pd.to_numeric)

    model = Prophet().fit(data)
#    model.fit(data)
    print(i,"model_fit")

    forecast = model.predict(last_3year)
    print(i,"model_predict")
    gangnam_predict = pd.concat([gangnam_predict, forecast['yhat']], ignore_index = True, axis=1)

04:45:58 - cmdstanpy - INFO - Chain [1] start processing
04:45:59 - cmdstanpy - INFO - Chain [1] done processing

0 model_fit
0 model_predict

TypeError: Invalid object type at position 0

In [88]:
gangnam_predict = pd.concat([gangnam_predict, forecast['ds']], ignore_index = True, axis=1)

gangnam_predict.columns = ['강남구', 'Date']

In [90]:
gangnam_predict.to_csv('gangnam_all_predict.csv', encoding='cp949',index = False)

In [124]:
gu_name = ['강동구', 'Date']

last_3year = list()
for i in range(2023, 2027):
    for j in range(1, 13):
        last_3year.append(['%04d-%02d' % (i,j)])
        
        
last_3year = pd.DataFrame(last_3year, columns = ['ds'])
last_3year['ds']= pd.to_datetime(last_3year['ds'])

for i in range(len(df['Date'])):
    date_time_str = df['Date'][i]
    
    date = datetime.datetime.strptime(str(date_time_str), '%Y%m')  #datetime.datetime.strptime(date, "%Y-%m-%d")
    
    df['Date'][i] = date

gangdong_predict = pd.DataFrame()

for i,name in enumerate(gu_name):
    data = pd.DataFrame()
    data = df[[name,'Date']]
    data.columns = ['y','ds']
    data['ds'] = pd.to_datetime(data['ds'])

    model = Prophet().fit(data)
    print(i,"model_fit")
    forecast = model.predict(last_3year)
    print(i,"model_predict")
    gangdong_predict = pd.concat([gangdong_predict, forecast['yhat']], ignore_index = True, axis=1)

04:57:56 - cmdstanpy - INFO - Chain [1] start processing
04:57:57 - cmdstanpy - INFO - Chain [1] done processing

0 model_fit
0 model_predict

TypeError: Invalid object type at position 0

In [125]:
gangdong_predict = pd.concat([gangdong_predict, forecast['ds']], ignore_index = True, axis=1)

gangdong_predict.columns = ['강동구', 'Date']

gangdong_predict.to_csv('gangndong_all_predict.csv', encoding='cp949',index = False)